include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - unawaited_futures
    - recursive_getters
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
    - sort_child_properties_last

analyzer:
  plugins:
    - custom_lint
